cache:
  key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.cache/pip

pylint:
  image: python:3.8
  before_script:
    - python -m pip install pylint
  script:
    - pylint --jobs $(nproc) --exit-zero **/*.py

.base:
  image: $IMAGE
  before_script:
    - python -m pip install tox
  script:
    - tox -e $CI_JOB_NAME

py37-salt2019-crypt:
  extends: .base
  variables:
    IMAGE: python:3.7

ubuntu1804-py36-salt2017-crypt21:
  extends: .base
  variables:
    IMAGE: python:3.6

debian10-py37-salt2018-crypt26:
  extends: .base
  variables:
    IMAGE: python:3.7
