name: build

on:
  - push
  - pull_request

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.9
            name: Python 3.9 / Salt 3002
            env: py3-salt3002-crypt
          - python: 3.8
            name: Python 3.8 / Salt 3001
            env: py3-salt3001-crypt
          - python: 3.7
            name: Python 3.7 / Salt 3000
            env: py3-salt3000-crypt
          - python: 3.7
            name: Python 3.7 / Salt 2019
            env: py3-salt2019-crypt
          - python: 3.7
            name: Debian 10 (Python 3.7 / Salt 2018 / Cryptography 2.6)
            env: py3-salt2018-crypt26
          - python: 3.6
            name: Ubuntu 18.04 (Python 3.6 / Salt 2017 / Cryptography 2.1)
            env: py3-salt2017-crypt21

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip
      - run: pip install wheel tox
      - run: tox -e ${{ matrix.env }} -- -vv

  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install pylint
      - run: pylint --jobs $(nproc) --exit-zero **/*.py
