name: build

on:
  - push
  - pull_request

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Salt 3006
            env: py3-salt3006-crypt39
            python: '3.10'
          - name: Salt 3005
            env: py3-salt3005-crypt33
            python: '3.9'
          - name: Ubuntu 22.04
            env: py3-salt3004-crypt34
            python: '3.10'
          - name: Debian 11
            env: py3-salt3002-crypt33
            python: '3.9'

    steps:
      - uses: actions/checkout@v1
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python }}
      - run: pdm install --dev --no-self --no-default
      - run: pdm run tox -e ${{ matrix.env }} -- -vv

  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
      - run: pdm install --dev --no-self --no-default
      - run: pdm run black --check .
