name: pytest
on: push

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: python -m pip install --upgrade pip
      - run: pip install pylint
      - run: pylint --jobs $(nproc) --exit-zero **/*.py
