name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Salt 3007
            env: py3-salt3007-crypt42
            python: "3.10"
          - name: Salt 3006
            env: py3-salt3006-crypt39
            python: "3.10"

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --dev
      - run: uv run tox -e ${{ matrix.env }} -- -vv

  ruff-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: uv sync --dev
      - run: uv run ruff check --no-fix --diff

  ruff-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: uv sync --dev
      - run: uv run ruff format --diff --check
